### ISSUE TITLE
main.dol.hack.gzf Corrupt?

### ISSUE THREAD

**Issue by notchase** [FortuneStreetModding/Disassembly#1]
I import main.dol.hack.gzf in Ghidra 9.1.2 using the Gekko/Broadway Language without error.
The bytes view ends with (or when output as a .bin):
804b6a10    :  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 62 
804b6a20    :  61 64 5f 66

"bad_f"
In my original main.dol, I can find multiple references of "bad_function_call"

The main.dol produced causes Dolphin to hang.

I think something is either corrupted or some Ghidra settings were left out of the readme.

**Comment by Deflaktor** [comment]
I also tried exporting the main.dol from ghidra some time ago. It is a known issue of ghidra that it does not export correctly. See
https://github.com/NationalSecurityAgency/ghidra/issues/19#issuecomment-591596603
Therefore I created the yml files to define what is the difference to the original main.dol.
